version: '3.3'

services:
  email_blaster:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    volumes:
      # Mount ~/HoarderBot-config on the host to /config inside the container
      - ~/HoarderBot-config:/config:rw
